CREATE TABLE IF NOT EXISTS cursos (
    ID_CURSOS INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(256) NOT NULL,
    DESCRICAO VARCHAR(256) NOT NULL,
    BANNER BLOB,
    DATA_INCLUDE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_CURSOS)
)